"""initial migrate

Revision ID: 970b26492c93
Revises: 
Create Date: 2021-02-19 10:18:25.309675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970b26492c93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.drop_column('f_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register', schema=None) as batch_op:
        batch_op.add_column(sa.Column('f_name', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
